NAME = GEOTERM
DESCRIPTION = "Geoguessr calculator edition"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz -I.. 
CXXFLAGS = -Wall -Wextra -Oz -I..


# ----------------------------

include $(shell cedev-config --makefile)