NAME = GEOTERM
DESCRIPTION = "Geoguessr calculator edition"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz -Iinclude
CXXFLAGS = -Wall -Wextra -Oz -Iinclude
LIBS = -Llibs -lmsgpack


# ----------------------------

include $(shell cedev-config --makefile)